### ISSUE TITLE
need to setup config for manageable baud rate

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/target-nordic-nrf51822#1]
https://github.com/ARMmbed/mbed-drivers/pull/128
The default baud rate for console output has been changed to 115200 for mbed OS applications. I believe this is good in general, but may not work for nRF51822. The clock on nRF51822 runs at 32kHz, and would not be fast enough to drive UART at 115200baud. 

I’d like us to discuss this internally. We might need to change this config value for nRF51 targets to something that’s possible by the hardware.

**Comment by andresag01** [comment]
@rgrover : This has been taken care of in [this issue](https://github.com/ARMmbed/target-nordic-nrf51822/issues/4).

**Comment by rgrover** [comment]
yes, thanks.
