### ISSUE TITLE
YOTTA_CFG_MBED_OS_STDIO_DEFAULT_BAUD needs to be 9600

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/target-nordic-nrf51822#4]
YOTTA_CFG_MBED_OS_STDIO_DEFAULT_BAUD now defines the default baud rate to be 115200. We need to downgrade this to 9600 for the nRF51 targets; this is because we run out of a low-freq. clock for the nRF51.

we need to update the intermediate level targets to offer configs with default set to 9600

**Comment by andresag01** [comment]
I have committed the change directly https://github.com/ARMmbed/target-nordic-nrf51822/commit/20e70c43fe235c57f5679f471beeb68f70bc151e. @rgrover, let me know if this change is acceptable so that I can publish a new version of the change in yotta public registry. Thanks

**Comment by andresag01** [comment]
@rgrover : I believe that this change has been merged and module published to yotta.
